version: "3.8"
services:
  redis:
    image: redis
    networks:
      - deployml_network
  
  modelserver:
    build:
      context: ./modelserver
      dockerfile: Dockerfile-dev
    depends_on:
      - redis
    networks:
      - deployml_network
    env_file:
      - app.env
    volumes:
      - ./modelserver/app:/app
      - ./modelserver/dictionaries:/dictionaries
      - ./modelserver/models:/models

  webapi:
    build: ./webapi
    ports:
      - "8000:80"
    networks:
      - deployml_network
    depends_on:
      - redis
    env_file:
      - app.env
    volumes:
      - ./webapi/app:/app

  frontend:
    networks:
      - deployml_network
    depends_on: 
      - webapi
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes:
       - ./frontend:/app
       - /app/node_modules

networks:
  deployml_network:
